### ISSUE TITLE
Problem building Singularity container

### ISSUE THREAD

**Issue by prmunn** [rcorces/ArchR_docker#5]
Hi @rcorces,

Is this repository still pre-release? I'm attempting to build a Singularity container - the script appears to have gotten as far as the install of RStudio before encountering the following problem:

Installing BiocManager [1.30.16] ...
       OK [built from source]
Copying BiocManager [1.30.16] into the cache ...
       OK [copied 25 files in 0.011 seconds]
Error: failed to determine Bioconductor repositories
Traceback (most recent calls last):
9: renv::restore(prompt = FALSE)
8: renv_restore_run_actions(project, diff, current, lockfile, rebuild)
7: renv_retrieve(packages)
6: handler(package, renv_retrieve_impl(package))
5: renv_retrieve_impl(package)
4: renv_scope_bioconductor()
3: renv_bioconductor_repos()
2: stopf("failed to determine Bioconductor repositories")
1: stop(sprintf(fmt, ...), call. = call.)
Execution halted
FATAL:   failed to execute %post proc: exit status 1
FATAL:   While performing build: while running engine: while running /usr/local/libexec/singularity/bin/starter: exit status 255

Any ideas?

**Comment by rcorces** [comment]
This is still pre-release. We've gotten side tracked working on other things but will eventually return to this. In the meantime, its possible that @paupaiz could provide some input but it isnt our intention to support this repository yet.

**Comment by prmunn** [comment]
Ok - thanks
